name: twin_web
description: "Boodskap IoT Digital Twin Platform"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

scripts:
  generate:
    all: ./scripts/generate-all.sh
    translations: ./scripts/generate-translations.sh
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  launch:
    dev: flutter run --flavor dev --dart-define=flavor=dev
    qa: flutter run --flavor qa --dart-define=flavor=qa
    prod: flutter run --flavor prod --dart-define=flavor=prod
  test:
    all: flutter test
    exclude-goldens: flutter test --exclude-tags=golden
    goldens: flutter test --tags=golden test/presentation/goldens
    update-goldens: flutter test --tags=golden test/presentation/goldens --update-goldens
    e2e: patrol test --flavor=qa --dart-define=flavor=qa
  analyze: flutter analyze --fatal-infos --fatal-warnings
  format: dart format --set-exit-if-changed lib
  fix: dart fix --apply
  build:
    apk:
      dev: flutter build apk --flavor=dev --dart-define=flavor=dev --debug
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --debug
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --debug
    release-apk:
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --release --obfuscate --split-debug-info=debug-info
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --release --obfuscate --split-debug-info=debug-info
    appbundle:
      dev: flutter build appbundle --flavor=dev --dart-define=flavor=dev
      qa: flutter build appbundle --flavor=qa --dart-define=flavor=qa
      prod: flutter build appbundle --flavor=prod --dart-define=flavor=prod
    ios:
      dev: flutter build ios --flavor=dev --dart-define=flavor=dev --debug --no-codesign
      qa: flutter build ios --flavor=qa --dart-define=flavor=qa --debug --no-codesign
      prod: flutter build ios --flavor=prod --dart-define=flavor=prod --debug --no-codesign
    web:
      dev: flutter build web --dart-define=flavor=dev
      qa: flutter build web --dart-define=flavor=qa
      prod: flutter build web --dart-define=flavor=prod


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.0.3
  easy_localization: ^3.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  logger: ^2.0.1
  shared_preferences: ^2.0.18
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  easy_logger: ^0.0.2
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  flutter_displaymode: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/translations/
    - assets/
    - .env
    - .env.dev
    - .env.qa
    - .env.test
    - default.conf

patrol:
  app_name: flutter_template
  android:
    package_name: com.wednesday.flutter_template.qa
  ios:
    bundle_id: com.wednesday.flutterTemplate.qa